add checkaks

diff --git a/.github/actions/wo-create-aks-conn-cluster/action.yml b/.github/actions/wo-create-aks-conn-cluster/action.yml
--- a/.github/actions/wo-create-aks-conn-cluster/action.yml
+++ b/.github/actions/wo-create-aks-conn-cluster/action.yml
@@ -24,24 +24,34 @@ runs:
       shell: bash
       run: |
 
+        akscls="false"
         echo "check if cluster already exists "
-        aksName=$(az aks show --resource-group "${{ steps.siteinfo.outputs.rg }}" --name "${{ inputs.siteClsName }}" --subscription "${{ steps.siteinfo.outputs.subId }}" 2>&1) || true
+        aksName=$(az aks show --resource-group "${{ steps.siteinfo.outputs.rg }}" --name "${{ inputs.siteClsName }}" --subscription "${{ steps.siteinfo.outputs.subId }}" --query name 2>&1) || true
 
-        exit_code=$?
-        echo "exit code: $exit_code"
-        echo "aksName: $aksName"
+        # exit_code=$?
+        # echo "exit code: $exit_code"
+        # echo "aksName: $aksName"
 
-        if [[ $exit_code -eq 0 ]] && echo "$aksName" | grep -Eq "ResourceNotFound|InvalidApiVersionParameter|No HTTP|InvalidAPI"; then
-          echo "cluster does not exist.creating ... "
-          akscls="false"
-          akscon="false"
-        else
-          echo "CLUSTER already exists"
-          echo
-          exit 0
+        # if [[ $exit_code -eq 0 ]] && echo "$aksName" | grep -Eq "ResourceNotFound|InvalidApiVersionParameter|No HTTP|InvalidAPI|NoneType"; then
+        #   echo "cluster does not exist.creating ... "
+        #   akscls="false"
+        #   akscon="false"
+        # else
+        #   echo "CLUSTER already exists"
+        #   echo
+        #   exit 0
+        # fi
+
+        if [[ "$aksName" == "${{ inputs.siteClsName }}" ]]; then
+          echo "cluster exists. nothing to so"
+          akscls="true"
+          exit 0 
         fi
 
+        echo "akscls=$akscls" >> $GITHUB_OUTPUT
+
     - name: create cluster identity
+      if: ${{ steps.checkaks.outputs.akscls == 'false' }}
       id: clsid
       shell: bash
       run: |
@@ -50,6 +60,7 @@ runs:
         echo "clusterIdentity=$(az identity show --resource-group ${{ steps.siteinfo.outputs.rg }} --name ${{ steps.siteinfo.outputs.siteClsId }} --query id --output tsv)" >> $GITHUB_OUTPUT
 
     - name: Create AKS cluster
+      if: ${{ steps.checkaks.outputs.akscls == 'false' }}
       id: createaks
       shell: bash
       run: |
@@ -59,12 +70,14 @@ runs:
                       --name ${{ steps.siteinfo.outputs.siteClsName }} --node-count 2 --node-vm-size Standard_D2s_v5 --assign-identity ${{ steps.clsid.outputs.clusterIdentity }} --generate-ssh-keys
 
     - name: Get AKS Credentials
+      if: ${{ steps.checkaks.outputs.akscls == 'false' }}
       uses: Azure/aks-set-context@v3
       with:
         resource-group: ${{ steps.siteinfo.outputs.rg }}
         cluster-name: ${{ steps.siteinfo.outputs.siteClsName }}
 
     - name: get cluster context and arc connect cluster
+      if: ${{ steps.checkaks.outputs.akscls == 'false' }}
       id: connectedcluster
       shell: bash
       run: |
