debug

diff --git a/.github/workflows/wo-infra-deploy.yml b/.github/workflows/wo-infra-deploy.yml
--- a/.github/workflows/wo-infra-deploy.yml
+++ b/.github/workflows/wo-infra-deploy.yml
@@ -72,12 +72,12 @@ jobs:
         echo " --> Please re-run worklow with correct inputs"
         exit 1
 
-    - name: validate action inputs
-      if: ${{ github.event.inputs.action == 'none' && github.event.inputs.sites != 'none' && github.event.inputs.commands == 'no action' }}
-      run: |
-        echo " *** INPUT ERROR *** Missing action."
-        echo " --> Please re-run worklow with correct inputs"
-        exit 1
+    # - name: validate action inputs
+    #   if: ${{ github.event.inputs.action == 'none' && github.event.inputs.sites != 'none' && github.event.inputs.commands == 'no action' }}
+    #   run: |
+    #     echo " *** INPUT ERROR *** Missing action."
+    #     echo " --> Please re-run worklow with correct inputs"
+    #     exit 1
 
   call-wo-setuponly-arc-conn-cls:
     if: ${{ github.event.inputs.action == '(** AzArc connected **) wo-setup-woready-arc-cls' && github.event.inputs.sites != 'none' }}
