cosmetics and error handling

diff --git a/.github/workflows/wo-infra-deploy.yml b/.github/workflows/wo-infra-deploy.yml
--- a/.github/workflows/wo-infra-deploy.yml
+++ b/.github/workflows/wo-infra-deploy.yml
@@ -67,22 +67,22 @@ permissions:
 
 jobs:
 
-  action-validate:
-    runs-on: ubuntu-latest
+  # action-validate:
+  #   runs-on: ubuntu-latest
 
-    - name: validate site inputs
-      if: ${{ github.event.inputs.action != 'none' && github.event.inputs.sites == 'none' }}
-      run: |
-        echo "Missing site."
-        echo "Please re-run worklow with all inputs"
-        exit 1
+  #   - name: validate site inputs
+  #     if: ${{ github.event.inputs.action != 'none' && github.event.inputs.sites == 'none' }}
+  #     run: |
+  #       echo "Missing site."
+  #       echo "Please re-run worklow with all inputs"
+  #       exit 1
 
-    - name: validate action inputs
-      if: ${{ github.event.inputs.action == 'none' && github.event.inputs.sites != 'none' }}
-      run: |
-        echo "Missing action."
-        echo "Please re-run worklow with all inputs"
-        exit 1
+  #   - name: validate action inputs
+  #     if: ${{ github.event.inputs.action == 'none' && github.event.inputs.sites != 'none' }}
+  #     run: |
+  #       echo "Missing action."
+  #       echo "Please re-run worklow with all inputs"
+  #       exit 1
 
 
   call-wo-setuponly-arc-conn-cls:
